### ISSUE TITLE
Missing code from 'Creating Users in Firestore' on your YouTube video

### ISSUE THREAD

**Issue by andesappal** [tadaspetra/bookclub#31]
Hi Mr. Petra, how are you? 

I am finishing an app and found your video on creating a user on Firestore according to auth's uid very useful. However, I could not find the additional help from your source code. Would you mind uploading the code corresponding to your video? I would appreciate so much!

Thank you!

**Comment by tadaspetra** [comment]
No longer working on this repo

**Comment by tadaspetra** [comment]
Just read the comment, I'm currently working on a complete guide for this on my site https://hungrimind.com
